version: '3'

networks: 
  default: 
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    hostname: app
    build: .
    restart: always
    stdin_open: true
    tty: true
    env_file: 
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  
  db:
    hostname: db
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    hostname: redis
    image: redis:alpine
    ports:
      - 6379:6379

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: dev@dev.com.br
      PGADMIN_DEFAULT_PASSWORD: dev@1234
    ports:
      - 6001:80
    volumes:
      - ./db-backup:/var/lib/pgadmin
    depends_on:
      - db
    